apiVersion: v1
kind: Service
metadata:
  name: service-apig
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - name: gateway-port
    protocol: TCP
    nodePort: 30004
    port: 8082
    targetPort: gatewayport
