apiVersion: v1
kind: Pod
metadata:
  name: service-a
spec:
  containers:
  - name: service-a
    image: parthkarad/service-a
    ports:
    - containerPort: 8080
      name: service-a-port
---

apiVersion: v1
kind: Pod
metadata:
  name: service-b
spec:
  containers:
  - name: service-b
    image: parthkarad/service-b
    ports:
    - containerPort: 8081
      name: service-b-port
