apiVersion: v1
kind: Pod
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  containers:
  - name: service-a
    image: parthkarad/service-a
    ports:
    - containerPort: 8080
      name: service-a-port
---

apiVersion: v1
kind: Pod
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  containers:
  - name: service-b
    image: parthkarad/service-b
    ports:
    - containerPort: 8081
      name: service-b-port

---

apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    app: gateway
spec:
  containers:
  - name: api-gateway
    image: parthkarad/api-gateway
    ports:
    - containerPort: 8082
      name: gatewayport
