apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
  - name: service-a
    protocol: TCP
    port: 8080
    targetPort: service-a-port
---

apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
  - name: service-b
    protocol: TCP
    port: 8081
    targetPort: service-b-port
